apply plugin: 'maven-publish'

tasks.register('androidJavadocs', Javadoc) {
    source = android.sourceSets.main.java.sourceFiles
}

tasks.register('androidJavadocsJar', Jar) {
    archiveClassifier = 'javadoc'
    //basename = artifact_id
    from androidJavadocs.destinationDir
}

tasks.register('androidSourcesJar', Jar) {
    archiveClassifier = 'sources'
    //basename = artifact_id
    from android.sourceSets.main.java.sourceFiles
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = GROUP
            artifactId = ARTIFACT
            version VERSION_NAME

            afterEvaluate { project ->
                from components.release
            }
        }
    }
}